Class {
	#name : #TST,
	#superclass : #TBClientEvent,
	#instVars : [
		'id',
		'name',
		'active',
		'start'
	],
	#category : #'PolyglotricDBI-Events'
}

{ #category : #accessing }
TST >> active [
	^ active
]

{ #category : #accessing }
TST >> active: anObject [
	active := anObject
]

{ #category : #accessing }
TST >> id [
	^ id
]

{ #category : #accessing }
TST >> id: anObject [
	id := anObject
]

{ #category : #accessing }
TST >> name [
	^ name
]

{ #category : #accessing }
TST >> name: anObject [
	name := anObject
]

{ #category : #accessing }
TST >> start [
	^ start
]

{ #category : #accessing }
TST >> start: anObject [
	start := anObject
]
